// <auto-generated />
using System;
using CarRentalAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarRentalAPI.Migrations
{
    [DbContext(typeof(CarDbContext))]
    [Migration("20190526103554_CarDataAdd")]
    partial class CarDataAdd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarRentalAPI.Data.Model.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand");

                    b.Property<double>("Cost");

                    b.Property<string>("Description");

                    b.Property<string>("ImageUrl");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new { Id = 1, Brand = "test1", Cost = 31.0, Description = "Simple description1", ImageUrl = "Url1" },
                        new { Id = 2, Brand = "test2", Cost = 32.0, Description = "Simple description2", ImageUrl = "Url2" },
                        new { Id = 3, Brand = "test3", Cost = 33.0, Description = "Simple description3", ImageUrl = "Url3" }
                    );
                });

            modelBuilder.Entity("CarRentalAPI.Data.Model.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarId");

                    b.Property<int>("ClientAge");

                    b.Property<string>("ClientLastName");

                    b.Property<DateTime>("PickUpDate");

                    b.Property<string>("PickUpLocation");

                    b.Property<DateTime>("ReturnDate");

                    b.Property<string>("ReturnLocation");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("CarRentalAPI.Data.Model.Reservation", b =>
                {
                    b.HasOne("CarRentalAPI.Data.Model.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
